package DDG::Fathead::InternationalClassificationOfDiseases;

use DDG::Fathead;

primary_example_queries "ICD 0WP13JZ";

secondary_example_queries "ICD10 0YJF3ZZ";

description "International Classification of Diseases";

name "InternationalClassificationOfDiseases";

source "The Centers for Medicare and Medicaid Services";

code_url "https://duck.co/ia/view/international_classification_for_diseases_icd";

topics "special_interest";

category "reference";

attribution
    github => ['mkorvink', 'Michael Korvink'];

1;
