---
sudo: false
env:
  - PERL_LWP_SSL_VERIFY_HOSTNAME=0
cache:
  directories:
    - $HOME/.cpanm
    - $HOME/perl5/perlbrew/perls/5.16/lib
before_install:
  - export HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
  - git config --global user.name "Dist Zilla Plugin TravisCI"
  - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
install:
  - cpanm --quiet --notest Dist::Zilla
  - dzil authordeps | grep -ve '^\W' | xargs -n 5 -P 10 cpanm --notest --quiet
  - dzil listdeps | grep -ve '^\W' | cpanm --notest --quiet
language: perl
perl:
  - 5.16
script:
  - prove -lr -j1 t/
