#!/bin/bash

FATHEAD="$(basename $(pwd))"

./parse.sh &&
scp output.txt ddg:zeroclickinfo-fathead/"$FATHEAD"/ &&


ssh ddg '
    rm /tmp2/ddg/sources/*;
    eval $(perl -I\/usr/local/ddg.cpan/perl5/lib/perl5 -Mlocal::lib=/usr/local/ddg.cpan/perl5) &&
    FATHEAD_ID="$(grep firefox_about_config /usr/local/ddg/components/fathead/prepare.pl | awk '\''{print $3}'\'' | tr -d ,)" &&
    /usr/local/ddg/components/fathead/prepare.pl '"$FATHEAD"' &&
    sudo /bin/su -m postgres -c "
        psql waki postgres -c \"
            delete from pages where source=$FATHEAD_ID;
            COPY pages FROM '\''/tmp2/ddg/sources/$FATHEAD_ID.abstract.process.txt'\''\";"' &&

notify-send -i ~/ddg/duckduckgo-logo.png "<br><br><br><br><b>DEPLOYED FATHEAD</b>"

if [ "$(pgrep uzbl)" ]; then
    echo "uri https://$(whoami).duckduckgo.com/?q=$(head output.txt | awk '{print $1}')" >> ~/.config/uzbl/io/uzbl_fifo_*-1
fi
